const TIMELINE_EVENTS = [
  { year: "129 AC", title: "Death of Viserys I", tag: "neutral", type: "death",
    desc: "King Viserys I Targaryen dies at King's Landing, leaving the succession contested between his daughter Rhaenyra and his eldest son by Alicent Hightower." },
  { year: "129 AC", title: "Aegon II Crowned", tag: "green", type: "event",
    desc: "The Green faction moves quickly, crowning Aegon II in the Dragonpit before Rhaenyra can be told of her father's death." },
  { year: "129 AC", title: "Rhaenyra Declares War", tag: "black", type: "event",
    desc: "Denied the throne she was named heir to, Rhaenyra rallies Dragonstone and calls her bannermen to war. The Dance of the Dragons begins." },
  { year: "129 AC", title: "Death of Lucerys Velaryon", tag: "green", type: "death",
    desc: "Sent to Storm's End to seek an alliance, Prince Lucerys is confronted by his uncle Aemond on Vhagar; his dragon Arrax is killed in the ensuing storm, and Rhaenyra vows revenge." },
  { year: "129 AC", title: "“Blood and Cheese”", tag: "black", type: "death",
    desc: "In retaliation, two hired killers slip into the Red Keep and murder young Prince Jaehaerys, son of Aegon II and Helaena, ending any hope of peace between the factions." },
  { year: "129 AC", title: "Death of Helaena Targaryen", tag: "neutral", type: "death",
    desc: "Still tormented by the murder of her son, Helaena Targaryen takes her own life at the Red Keep, unable to bear the horror any longer." },
  { year: "129 AC", title: "Fall of Harrenhal", tag: "black", type: "battle",
    desc: "Daemon Targaryen claims the ruined seat of Harrenhal from House Strong with a single blast of dragonfire, giving the Blacks a foothold in the Riverlands." },
  { year: "129 AC", title: "Battle of the Gullet", tag: "black", type: "battle",
    desc: "Lord Corlys Velaryon's fleet and the Triarchy's ships clash at the mouth of Blackwater Bay, one of the largest naval battles in Westerosi history." },
  { year: "129 AC", title: "The Red Sowing", tag: "black", type: "event",
    desc: "At Dragonstone, low-born claimants of Valyrian blood step forward to bond with Rhaenyra's riderless dragons, among them Nettles, who tames the wild Sheepstealer." },
  { year: "129 AC", title: "First Battle of Tumbleton", tag: "green", type: "battle",
    desc: "A Green army under Lord Ormund Hightower and Ser Criston Cole routs Rhaenyra's Riverlands forces at Tumbleton." },
  { year: "129 AC", title: "Battle of the Redgrass Field", tag: "green", type: "battle",
    desc: "The single bloodiest battle of the war; Aegon II's army routs Rhaenyra's forces in the Reach at staggering cost, with thousands dead on both sides." },
  { year: "130 AC", title: "Battle of Rook's Rest", tag: "green", type: "battle",
    desc: "Prince Aemond's Vhagar kills Rhaenys Targaryen and her dragon Meleys, while Aegon II is grievously burned by dragonfire." },
  { year: "130 AC", title: "Death of Jacaerys Velaryon", tag: "black", type: "death",
    desc: "Flying Vermax in search of allies for his mother's cause, Prince Jacaerys is shot from the sky and killed." },
  { year: "130 AC", title: "Storming of the Dragonpit", tag: "neutral", type: "event",
    desc: "Smallfolk riot in King's Landing; three dragons are slain in the chaos, and the city falls into Rhaenyra's hands." },
  { year: "130 AC", title: "Rhaenyra Crowned Queen", tag: "black", type: "event",
    desc: "Rhaenyra Targaryen is crowned in the ruins of the Dragonpit, becoming the first ruling Queen of the Seven Kingdoms." },
  { year: "130 AC", title: "A Queen Undone", tag: "black", type: "event",
    desc: "Facing bare coffers, a starving city, and a court she cannot control, Rhaenyra's reign curdles into paranoia and executions, costing her what little support remained." },
  { year: "130 AC", title: "Death of Ormund Hightower", tag: "green", type: "death",
    desc: "Poisoned in the field not long after his victory at Tumbleton, Lord Ormund Hightower dies, leaving Ser Criston Cole to take sole command of the Green army." },
  { year: "130 AC", title: "Rhaenyra Flees King's Landing", tag: "green", type: "event",
    desc: "As Aegon II's forces close in and the smallfolk turn on her, Rhaenyra abandons the capital with her young son, attempting to reach safety by ship." },
  { year: "130 AC", title: "Death of Rhaenyra", tag: "green", type: "death",
    desc: "Captured and brought back to King's Landing, Rhaenyra Targaryen is executed on Aegon II's orders, killed by his dragon Sunfyre. It's the war's most infamous death." },
  { year: "131 AC", title: "Second Battle of Tumbleton", tag: "black", type: "battle",
    desc: "A chaotic night battle and dragonfire shatter the Green army encamped at Tumbleton." },
  { year: "131 AC", title: "Death of Ser Criston Cole", tag: "green", type: "death",
    desc: "Betrayed by turncloak dragonseeds in the chaos of the Second Battle of Tumbleton, the Green army's commander is killed and his forces scattered." },
  { year: "131 AC", title: "Battle Above the Gods Eye", tag: "neutral", type: "battle",
    desc: "The last of the war's great dragons die in single combat over the lake, leaving House Targaryen's dragon population devastated." },
  { year: "131 AC", title: "Death of Daemon Targaryen", tag: "black", type: "death",
    desc: "Daemon Targaryen falls in the God's Eye duel, taking Prince Aemond and both their dragons, Caraxes and Vhagar, down with him." },
  { year: "131 AC", title: "Death of Aegon II", tag: "green", type: "death",
    desc: "Poisoned in the war's final days, Aegon II dies having reigned only a short and troubled time." },
  { year: "131 AC", title: "Aegon III Crowned", tag: "neutral", type: "event",
    desc: "Rhaenyra's son Aegon III takes the Iron Throne as a child king, ending the Dance of the Dragons and beginning a long, fragile peace." }
];
